#!/bin/csh
#
#  make the lute8 font
#
# xdvi
#
set FMT = /usr/people/wbc/src/lute/wplain
set FMT = plain
#
# virmf \&$FMT "\mode:=bitgraph; \mag:=1.0; input lute9; bye;"
# gftopk ./lute9.118gf > ./lute9.118pk
# mv lute9.118pk /usr/lib/tex/fonts/pk118/lute9.118pk
#
# laserwriter
#
virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input lute9; bye;"
gftopk ./lute9.300gf > ./lute9.300pk
mv lute9.300pk /usr/lib/tex/fonts/pk300/lute9.300pk
cp lute9.tfm /usr/lib/tex/fonts/tfm
#
#clean up
#
rm -f lute9*gf lute9*bdf lute9.log
#
# reduced font
#
#virmf \&$FMT "\mode:=bitgraph; \mag:=1.0; input lute6; bye;"
#gftopk ./lute6.118gf > ./lute6.118pk
#mv lute6.118pk /usr/lib/tex/fonts/pk118/lute6.118pk
#
# laserwriter
#
virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input lute6; bye;"
gftopk ./lute6.300gf > ./lute6.300pk
mv lute6.300pk /usr/lib/tex/fonts/pk300/lute6.300pk
#cp lute6.tfm /usr/lib/tex/fonts/tfm
#
#clean up
#
rm -f lute6*gf lute6*bdf lute6.log
#
# less reduced font
#
# virmf \&$FMT "\mode:=bitgraph; \mag:=1.0; input lute8; bye;"
# gftopk ./lute8.118gf > ./lute8.118pk
# mv lute8.118pk /usr/lib/tex/fonts/pk118/lute8.118pk
#
# laserwriter
#
virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input lute8; bye;"
gftopk ./lute8.300gf > ./lute8.300pk
mv lute8.300pk /usr/lib/tex/fonts/pk300/lute8.300pk
cp lute8.tfm /usr/lib/tex/fonts/tfm
#
#clean up
#
rm -f lute8*gf lute8*bdf lute8.log
#
#
# less less reduced font
#
# virmf \&$FMT "\mode:=bitgraph; \mag:=1.0; input lute7; bye;"
# gftopk ./lute7.118gf > ./lute7.118pk
# mv lute7.118pk /usr/lib/tex/fonts/pk118/lute7.118pk
#
# laserwriter
#
virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input lute7; bye;"
gftopk ./lute7.300gf > ./lute7.300pk
mv lute7.300pk /usr/lib/tex/fonts/pk300/lute7.300pk
cp lute7.tfm /usr/lib/tex/fonts/tfm
#
#clean up
#
rm -f lute7*gf lute7*bdf lute7.log


