#!/bin/csh
#
#  make the lute8 font
#
#
#
set FMT = plain
#
#
# laserwriter
#
#
# virmf \&$FMT "\mode:=CompugraphicNineSixZeroZero; \mag:=1.0; input lute9; bye;"
virmf \&$FMT "\mode:=VarityperFourThreeZeroZeroLo; \mag:=1.0; input lute9; bye;"
gftopk ./lute9.1200gf > ./lute9.1200pk
#
# virmf \&$FMT "\mode:=ultre; \mag:=1.0; input blute9; bye;"
# gftopk ./blute9.1200gf > ./blute9.1200pk
#
#rm -f lute9*gf lute9*bdf lute9.log
#
if ($#argv > 0 ) then
	echo foo
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute85; bye;"
  gftopk ./blute85.300gf > ./blute85.300pk
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute8; bye;"
  gftopk ./blute8.300gf > ./blute8.300pk
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute7; bye;"
  gftopk ./blute7.300gf > ./blute7.300pk
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute6; bye;"
  gftopk ./blute6.300gf > ./blute6.300pk
endif
