#!/bin/csh
#
#  make the lute font
# set FMT = plain
#
# laserwriter
# vtftzzlo
#
## mf "\mode:=vtftzzlo; \mag:=1.0; input lute9; bye;"
## gftopk ./lute9.1200gf > ./lute9.1200pk
#
mf "\mode:=vtftzzlo; \mag:=1.0; \wid#:=2.5pt#; input blute9; bye;"
gftopk ./blute9.1200gf > ./blute9.1200pk
#
# virmf \&$FMT "\mode:=ultre; \mag:=1.0; input blute9; bye;"
# gftopk ./blute9.1200gf > ./blute9.1200pk
#
#rm -f lute9*gf lute9*bdf lute9.log
#
if ($#argv > 0 ) then
	echo foo
#  mf "\mode:=vtftzzlo; \mag:=1.0; input blute9; bye;"
#  gftopk ./blute9.1200gf > ./blute9.1200pk
  mf "\mode:=vtftzzlo; \mag:=1.0; input blute85; bye;"
  gftopk ./blute85.1200gf > ./blute85.1200pk
  mf "\mode:=vtftzzlo; \mag:=1.0; input blute8; bye;"
  gftopk ./blute8.1200gf > ./blute8.1200pk
  mf "\mode:=vtftzzlo; \mag:=1.0; input blute7; bye;"
  gftopk ./blute7.1200gf > ./blute7.1200pk
  mf "\mode:=vtftzzlo; \mag:=1.0; input blute6; bye;"
  gftopk ./blute6.1200gf > ./blute6.1200pk
#  mf "\mode:=vtftzzlo; \mag:=1.0; input lute9; bye;"
#  gftopk ./lute9.1200gf > ./lute9.1200pk
  mf "\mode:=vtftzzlo; \mag:=1.0; input lute85; bye;"
  gftopk ./lute85.1200gf > ./lute85.1200pk
  mf "\mode:=vtftzzlo; \mag:=1.0; input lute8; bye;"
  gftopk ./lute8.1200gf > ./lute8.1200pk
  mf "\mode:=vtftzzlo; \mag:=1.0; input lute7; bye;"
  gftopk ./lute7.1200gf > ./lute7.1200pk
  mf "\mode:=vtftzzlo; \mag:=1.0; input lute6; bye;"
  gftopk ./lute6.1200gf > ./lute6.1200pk
endif
