#!/bin/perl
#
#  make the lute font
#
# some 2400 modes are supre and vtftzzhi
# some 1200 modes are vtftzzlo laserwriter lexmarkr ljfzzzfr
# some 600 modes are  canonex ljfzzzfr ljfive docutech
# some 300 modes are cx
#
my $bpi = $ARGV[0];
#
#$bpi = "600";
#
$mode = "vtftzzhi";    #2400
if ($bpi eq "2400") {$mode = "vtftzzhi";}    #2400
elsif ($bpi eq "1200") {$mode = "vtftzzlo";}    #1200
elsif ($bpi eq "600")  {$mode = "docutech";}    # 600
elsif ($bpi eq "300")  {$mode = "cx";}          # 300
else {
    printf("size must be one of 300 600 1200 2400\n");
    exit;
}
						
#
$fmt = "plain";
$pk = $bpi . "pk";
$gf = $bpi . "gf";
#
#  "85" doesn't work 
# foreach $size ("9", "85", "8", "7", "6") {
foreach $size ("9", "85",  "8", "7", "6") {
    foreach $lute ( "lute", "blute") {
	print "SIZE is $size \n";
	$command = "mf \\&${fmt} ";
	$command = "mf ";
	$command = $command . "\"\\mode:=" . $mode . "; \\mag:=1.0; input ${lute}${size}" .  "; bye;\"";
	print  "$command\n";
	system "$command\n";
	print  ("gftopk ./${lute}${size}.$gf > ./${lute}${size}.$pk \n");
	system ("gftopk ./${lute}${size}.$gf > ./${lute}${size}.$pk \n");
    }
}

#system ("mf \\&$FMT \"\mode:=$mode; \mag:=1.0; input lute9; bye;\");
#system ("gftopk ./lute9.$bpi > ./lute9.$pk");
#
# virmf \&$FMT "\mode:=ultre; \mag:=1.0; input blute9; bye;"
# gftopk ./blute9.2400gf > ./blute9.2400pk
#
