#!/bin/csh
#
#  make the lute8 font
#
# virmf means run mf with the "plain" base which is the same as the "mf" base
#
#
set FMT = plain
#
set MFINPUTS = "/usr/share/texlive/texmf-dist/metafont/base/"
#
#
# some 2400 modes are
# supre and vtftzzh
#
# mf \&$FMT "\mode:=supre; \mag:=1.0; input lute9; bye;"
mf \&plain "\mode:=CanonCX; \mag:=1.0; input  lute9; bye;"

gftopk ./lute9.2400gf > ./lute9.2400pk
#
# mf \&$FMT "\mode:=ultre; \mag:=1.0; input blute9; bye;"
# gftopk ./blute9.2400gf > ./blute9.2400pk
#
#rm -f lute9*gf lute9*bdf lute9.log
#
if ($#argv > 0 ) then
	echo foo
  mf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute85; bye;"
  gftopk ./blute85.300gf > ./blute85.300pk
  mf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute8; bye;"
  gftopk ./blute8.300gf > ./blute8.300pk
  mf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute7; bye;"
  gftopk ./blute7.300gf > ./blute7.300pk
  mf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute6; bye;"
  gftopk ./blute6.300gf > ./blute6.300pk
endif
