#!/bin/csh
#
#  make the lute9 font
#
#
set FMT = plain
#
# 600 dpi ...
# ljfour  canonex docutech lexmarku ljfive ljfzzzfr okifte qmsostf qmsoszz ricohsp vtszz
# 
# 
set MODE=CanonCX
mode=cx
#set MODE=docutech
# set MODE=cxnew
#
# if using precompiled modes set here, otherwise in lute9
#
# note - aug 2002 - mode doesn't seem to do much
# here, overridden in lute9.mf most likely.
# but it is needed for the command line, don't know why.
# but it means fixing the mode in lute9.mf for different dpi
# mag:=1.0 is default, no need to specify
#
#
#
if ($#argv == 0  ) then
  mf "\mode:=$MODE; \mag:=1.0; input lute9; bye;"
  gftopk ./lute9.300gf > ./lute9.300pk
  rm ./lute9.300gf
  mf "\mode:=$MODE; \mag:=1.0; input lute8; bye;"
  gftopk ./lute8.300gf > ./lute8.300pk
  rm ./lute8.300gf
  mf "\mode:=$MODE; \mag:=1.0; input lute7; bye;"
  gftopk ./lute7.300gf > ./lute7.300pk
  rm ./lute7.300gf
  mf "\mode:=$MODE; \mag:=1.0; input lute6; bye;"
  gftopk ./lute6.300gf > ./lute6.300pk
  rm ./lute6.300gf
  rm lute*log lute*300gf
else  
  if ( $1 == 'b' ) then
    echo baroque font
    mf "\mode:=$MODE; \mag:=1.0; input blute9; bye;"
    gftopk ./blute9.300gf > ./blute9.300pk
    mf "\mode:=$MODE; \mag:=1.0; input blute85; bye;"
    gftopk ./blute85.300gf > ./blute85.300pk
    mf "\mode:=$MODE; \mag:=1.0; input blute8; bye;"
    gftopk ./blute8.300gf > ./blute8.300pk
    mf "\mode:=$MODE; \mag:=1.0; input blute7; bye;"
    gftopk ./blute7.300gf > ./blute7.300pk
    mf "\mode:=$MODE; \mag:=1.0; input blute6; bye;"
    gftopk ./blute6.300gf > ./blute6.300pk
    rm blute*log blute*300gf
  else
    echo args:  b
  endif
endif
#

