#!/bin/csh
#
#  make the lute8 font
#
#
#
set FMT = plain
#
#
# laserwriter
#
#
# virmf \&$FMT "\mode:=IBMFourZeroTwoNine; \mag:=1.0; input blute9; bye;"
#
# was IBMFourZeroTwoNine;laserjetIV;
set MODE=ljfour
#
virmf \&$FMT "\mode:=$MODE; \mag:=1.0; input lute9; bye;"
gftopk ./lute9.600gf > ./lute9.600pk
#
#rm -f lute9*gf lute9*bdf lute9.log
#
if ($#argv > 0  ) then
 echo $argv[1]
 if ( $argv[1] != 'b' ) then
	echo foo
#  virmf \&$FMT "\mode:=$MODE; \mag:=1.0; input lute85; bye;"
#  gftopk ./lute85.600gf > ./lute85.600pk
  virmf \&$FMT "\mode:=$MODE; \mag:=1.0; input lute8; bye;"
  gftopk ./lute8.600gf > ./lute8.600pk
  virmf \&$FMT "\mode:=$MODE; \mag:=1.0; input lute7; bye;"
  gftopk ./lute7.600gf > ./lute7.600pk
  virmf \&$FMT "\mode:=$MODE; \mag:=1.0; input lute6; bye;"
  gftopk ./lute6.600gf > ./lute6.600pk
 else  
  virmf \&$FMT "\mode:=$MODE; \mag:=1.0; input blute9; bye;"
  gftopk ./blute9.600gf > ./blute9.600pk
  virmf \&$FMT "\mode:=$MODE; \mag:=1.0; input blute85; bye;"
  gftopk ./blute85.600gf > ./blute85.600pk
  virmf \&$FMT "\mode:=$MODE; \mag:=1.0; input blute8; bye;"
  gftopk ./blute8.600gf > ./blute8.600pk
  virmf \&$FMT "\mode:=$MODE; \mag:=1.0; input blute7; bye;"
  gftopk ./blute7.600gf > ./blute7.600pk
  virmf \&$FMT "\mode:=$MODE; \mag:=1.0; input blute6; bye;"
  gftopk ./blute6.600gf > ./blute6.600pk
 endif
endif
