#!/bin/csh
#
#  make the lute8 font
#
#
#
set FMT = plain
#
# laserwriter
# virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input lute9; bye;"
# gftopk ./lute9.300gf > ./lute9.300pk
##
virmf \&$FMT "\mode:=cxnew; \mag:=1.0; input blute9; bye;"
gftopk ./blute9.600gf > ./blute9.600pk
##
virmf \&$FMT "\mode:=cxnew; \mag:=1.0; input blute85; bye;"
gftopk ./blute85.600gf > ./blute85.600pk
##
virmf \&$FMT "\mode:=cxnew; \mag:=1.0; input blute8; bye;"
gftopk ./blute8.600gf > ./blute8.600pk
##
virmf \&$FMT "\mode:=cxnew; \mag:=1.0; input blute7; bye;"
gftopk ./blute7.600gf > ./blute7.600pk
## 
virmf \&$FMT "\mode:=cxnew; \mag:=1.0; input blute6; bye;"
gftopk ./blute6.600gf > ./blute6.600pk
## 
#
#
#if ($#argv > 0 ) then
#	echo foo
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute85; bye;"
  gftopk ./blute85.300gf > ./blute85.300pk
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute8; bye;"
  gftopk ./blute8.300gf > ./blute8.300pk
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute7; bye;"
  gftopk ./blute7.300gf > ./blute7.300pk
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute6; bye;"
  gftopk ./blute6.300gf > ./blute6.300pk
#endif
