#!/bin/csh
#
#  make the lute8 font
#
#
#
set FMT = plain
#
#
# laserwriter
# virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input lute9; bye;"
# gftopk ./lute9.300gf > ./lute9.300pk
##
virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute9; bye;"
gftopk ./blute9.300gf > ./blute9.300pk
##
## virmf \&$FMT "\mode:=IBMFourZeroTwoNine; \mag:=1.0; input blute9; bye;"
#virmf \&$FMT "\mode:=laserjetIV; \mag:=1.0; input blute9; bye;"
##virmf \&$FMT "\mode:=MyLaser; \mag:=1.0; input blute9; bye;"
#gftopk ./blute9.600gf > ./blute9.600pk
##
#rm -f lute9*gf lute9*bdf lute9.log
#
if ($#argv > 0 ) then
	echo foo
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute85; bye;"
  gftopk ./blute85.300gf > ./blute85.300pk
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute8; bye;"
  gftopk ./blute8.300gf > ./blute8.300pk
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute7; bye;"
  gftopk ./blute7.300gf > ./blute7.300pk
  virmf \&$FMT "\mode:=CanonCX; \mag:=1.0; input blute6; bye;"
  gftopk ./blute6.300gf > ./blute6.300pk
endif
